### ISSUE TITLE
Proposal: I think we should remove "@" from the internal variable

### ISSUE THREAD

**Issue by Toshinori-Hayashi** [sheo0147/CEoR#14]
The internal variable "$__RUSR" is as follows.
    `USERNAME@`

"@" is added just to generate SSH options easily.

Just because you don't want to write "@" in your source code, it's not right to give other users unnecessary pain to use this variable.

-- JAPANESE -------------------------------------------------------------------

内部変数から＠を取り除くべきだと思います。

内部変数"$__RUSR" は以下のように構成されています
    `USERNAME@`

sshのオプションを容易に生成するだけのために「＠」が付加されています。
ソースコードで「＠」を書きたくないだけで、他のユーザがこの変数を使う為にわざわざ”＠”を削除しなくてはならないのは本末転倒だと思います

**Comment by sheo0147** [comment]
OK.
fixed.

**Comment by sheo0147** [comment]
I fixed it. close.
