### ISSUE TITLE
Proposal: I want SSH authentication without using ssh_config.

### ISSUE THREAD

**Issue by Toshinori-Hayashi** [sheo0147/CEoR#8]
The setting used only in Ceor is desirable to complete within the ceor.

-- Japanese -------------------------------------------------------------------------------
ssh_configを利用せずにssh認証したい。
CEoRのみで利用する設定は、CEoR内で完結するのが望ましい。

**Comment by sheo0147** [comment]
I think you are true.
But it is hard to improve in this version of CEoR.
I add it with next version.

**Comment by sheo0147** [comment]
Support SSH_CONFIG environment for all ssh connection.
for ex.
Add 'SSH_CONFIG: ./.ssh/config' to ./.CEoR/ceor.conf.local and create ./.ssh/config

**Comment by sheo0147** [comment]
ssh has many options, so please use SSH_CONFIG.
